//------------------------------------------------------------------------------
// File        : fifo_write_only_test.sv
// Description : Write-only directed test for asynchronous FIFO.
//
// Test Plan ID:
//   FIFO_TC_004 : write_only_test
//
// Objective:
//   Verify that multiple write requests are accepted and stored in the FIFO
//   when no read requests are generated.
//
// Test Flow:
//   1. Wait for initial reset release.
//   2. Check post-reset FIFO flags.
//   3. Perform NUM_WRITES writes using directed unique data.
//   4. Do not issue any read request.
//   5. Wait until read domain observes FIFO non-empty state.
//   6. Check scoreboard counts and expected queue occupancy.
//------------------------------------------------------------------------------

class fifo_write_only_test extends fifo_base_test;
import fifo_tb_config_pkg::*;
  
  `uvm_component_utils(fifo_write_only_test)

  //--------------------------------------------------------------------------
  // Test Configuration
  //--------------------------------------------------------------------------

  
  localparam int unsigned NUM_WRITES = 4;

  //--------------------------------------------------------------------------
  // Constructor
  //--------------------------------------------------------------------------

  function new(
    string name = "fifo_write_only_test",
    uvm_component parent = null
  );
    super.new(name, parent);
  endfunction

  //--------------------------------------------------------------------------
  // wait_for_non_empty
  //
  // Wait for read-domain `rempty` flag to deassert.
  //
  // After a write, the write pointer passes through a two-flop synchronizer
  // before read-side logic can observe the write. Therefore, rempty does not
  // necessarily deassert immediately after the write sequence finishes.
  //--------------------------------------------------------------------------

  task automatic wait_for_non_empty(
    input time timeout_value = 1_000ns
  );

    bit non_empty_seen;

    non_empty_seen = 1'b0;

    fork
      begin
        wait (vif.rempty === 1'b0);
        non_empty_seen = 1'b1;
      end

      begin
        #timeout_value;
      end
    join_any

    disable fork;

    if (!non_empty_seen) begin
      `uvm_fatal(
        "WRITE_ONLY_TEST",
        $sformatf(
          "Timeout waiting for FIFO to become non-empty. rempty=%0b",
          vif.rempty
        )
      )
    end

    `uvm_info(
      "WRITE_ONLY_TEST",
      "Read domain observed FIFO non-empty condition: rempty=0",
      UVM_LOW
    )

  endtask

  //--------------------------------------------------------------------------
  // run_phase
  //--------------------------------------------------------------------------

  task run_phase(uvm_phase phase);

    fifo_write_sequence write_seq;

    // Only test class owns objections.
    phase.raise_objection(this);

    `uvm_info(
      "WRITE_ONLY_TEST",
      "Starting write-only FIFO test",
      UVM_LOW
    )

    //------------------------------------------------------------------------
    // Step 1: Wait for initial reset generated by tb_top.
    //------------------------------------------------------------------------
    wait_for_initial_reset_release();

    //------------------------------------------------------------------------
    // Step 2: Verify expected post-reset state.
    //------------------------------------------------------------------------
    check_initial_reset_state();

    //------------------------------------------------------------------------
    // Step 3: Generate write burst.
    //
    // No read sequence is started in this test.
    //------------------------------------------------------------------------
    write_seq = fifo_write_sequence::type_id::create("write_seq");

    write_seq.num_writes = NUM_WRITES;

    write_seq.start(env.wagent.wseqr);

    `uvm_info(
      "WRITE_ONLY_TEST",
      $sformatf(
        "Completed %0d write attempts",
        NUM_WRITES
      ),
      UVM_LOW
    )

    //------------------------------------------------------------------------
    // Step 4: Wait for write pointer synchronization into read domain.
    //------------------------------------------------------------------------
    wait_for_non_empty();

    // Give write monitor and scoreboard one or two cycles to complete all
    // analysis-port transactions before checking counters.
    repeat (2) @(posedge vif.rclk);

    //------------------------------------------------------------------------
    // Step 5: Check expected write behavior.
    //------------------------------------------------------------------------

    // All write attempts should be accepted because NUM_WRITES < DEPTH.
    if (env.sb.accepted_write_count != NUM_WRITES) begin
      `uvm_error(
        "WRITE_ONLY_TEST",
        $sformatf(
          "Accepted write count mismatch. Expected=%0d Actual=%0d",
          NUM_WRITES,
          env.sb.accepted_write_count
        )
      )
    end


    // No read sequence was started.
    if (env.sb.accepted_read_count != 0) begin
      `uvm_error(
        "WRITE_ONLY_TEST",
        $sformatf(
          "Expected 0 accepted reads, observed %0d",
          env.sb.accepted_read_count
        )
      )
    end



    // Read domain must observe available data after CDC synchronization.
    if (vif.rempty !== 1'b0) begin
      `uvm_error(
        "WRITE_ONLY_TEST",
        $sformatf(
          "Expected rempty=0 after writes, actual rempty=%0b",
          vif.rempty
        )
      )
    end

    `uvm_info(
      "WRITE_ONLY_TEST",
      $sformatf(
        "Write-only test passed. FIFO model occupancy=%0d/%0d",
        env.sb.expected_q.size(),
        DEPTH
      ),
      UVM_LOW
    )

    phase.drop_objection(this);

  endtask

endclass
