//------------------------------------------------------------------------------
// File        : fifo_multiple_write_read_test.sv
// Description : Multiple write and multiple read FIFO ordering test.
//
// Test Plan ID:
//   FIFO_TC_003 : multiple_write_read_test
//
// Objective:
//   Verify that multiple FIFO entries are read in exactly the same order in
//   which they were accepted on the write interface.

//------------------------------------------------------------------------------

class fifo_multiple_write_read_test extends fifo_base_test;

  `uvm_component_utils(fifo_multiple_write_read_test)

  // Number of FIFO entries used in this test.
  localparam int unsigned NUM_TRANSFERS = 10;


  //--------------------------------------------------------------------------
  // Constructor
  //--------------------------------------------------------------------------
  function new(
    string name = "fifo_multiple_write_read_test",
    uvm_component parent = null
  );
    super.new(name, parent);
  endfunction

  //--------------------------------------------------------------------------
  // wait_for_non_empty
  //
  // Wait until the read domain detects at least one available FIFO entry.
  //--------------------------------------------------------------------------
  task automatic wait_for_non_empty(
    input time timeout_value = 1_000ns
  );

    bit non_empty_seen = 1'b0;

    fork
      begin
        wait (vif.rempty === 1'b0);
        non_empty_seen = 1'b1;
      end

      begin
        #timeout_value;
      end
    join_any

    disable fork;

    if (!non_empty_seen) begin
      `uvm_fatal(
        "MULTI_WR_RD_TEST",
        $sformatf(
          "Timeout waiting for rempty to deassert. rempty=%0b",
          vif.rempty
        )
      )
    end

    `uvm_info(
      "MULTI_WR_RD_TEST",
      "Read domain detected FIFO non-empty condition",
      UVM_LOW
    )

  endtask

  //--------------------------------------------------------------------------
  // wait_for_empty
  //
  // Wait until the read domain detects that all entries were consumed.
  //--------------------------------------------------------------------------
  task automatic wait_for_empty(
    input time timeout_value = 1_000ns
  );

    bit empty_seen = 1'b0;

    fork
      begin
        wait (vif.rempty === 1'b1);
        empty_seen = 1'b1;
      end

      begin
        #timeout_value;
      end
    join_any

    disable fork;

    if (!empty_seen) begin
      `uvm_fatal(
        "MULTI_WR_RD_TEST",
        $sformatf(
          "Timeout waiting for rempty to assert. rempty=%0b",
          vif.rempty
        )
      )
    end

    `uvm_info(
      "MULTI_WR_RD_TEST",
      "Read domain detected FIFO empty condition",
      UVM_LOW
    )

  endtask

  //--------------------------------------------------------------------------
  // run_phase
  //--------------------------------------------------------------------------
  task run_phase(uvm_phase phase);

    fifo_write_sequence write_seq;
    fifo_read_sequence  read_seq;

    phase.raise_objection(this);

    `uvm_info(
      "MULTI_WR_RD_TEST",
      "Starting multiple write/read FIFO ordering test",
      UVM_LOW
    )

    // Step 1: Wait for reset generated by tb_top.
    wait_for_initial_reset_release();
    check_initial_reset_state();

    //------------------------------------------------------------------------
    // Step 2: Write four directed data values.
    //------------------------------------------------------------------------
    write_seq = fifo_write_sequence::type_id::create(
      "write_seq"
    );

    write_seq.num_writes = NUM_TRANSFERS;
   
    write_seq.start(env.wagent.wseqr);

    `uvm_info(
      "MULTI_WR_RD_TEST",
      $sformatf(
        "Completed %0d write attempts",
        NUM_TRANSFERS
      ),
      UVM_LOW
    )

    // Wait for pointer synchronization from write to read domain.
    wait_for_non_empty();

    //------------------------------------------------------------------------
    // Step 3: Request four reads.
    //------------------------------------------------------------------------
    read_seq = fifo_read_sequence::type_id::create(
      "read_seq"
    );

    read_seq.num_reads = NUM_TRANSFERS;

    read_seq.start(env.ragent.rseqr);

    `uvm_info(
      "MULTI_WR_RD_TEST",
      $sformatf("Completed %0d read attempts", NUM_TRANSFERS),
      UVM_LOW
    )

    // Step 4: FIFO must become empty after all four entries are read.
    wait_for_empty();

    // Allow monitor and scoreboard analysis transactions to complete.
    repeat (2) @(posedge vif.rclk);

    `uvm_info(
      "MULTI_WR_RD_TEST",
      "Multiple write/read FIFO ordering test completed",
      UVM_LOW
    )

    phase.drop_objection(this);

  endtask

      
endclass
