//------------------------------------------------------------------------------
// File        : fifo_reset_test.sv
// Description : UVM reset test for asynchronous FIFO.
//
// Test Plan ID:
//   FIFO_TC_001 : reset_test
//
// Objective:
//   Verify the expected FIFO status flags after initial reset release.
// Important:
//   rdata is not checked because FIFO memory is not reset and rdata is not
//   functionally valid while rempty=1.
//------------------------------------------------------------------------------

class fifo_reset_test extends fifo_base_test;

  `uvm_component_utils(fifo_reset_test)

  //--------------------------------------------------------------------------
  // Constructor
  //--------------------------------------------------------------------------
  function new(
    string name = "fifo_reset_test",
    uvm_component parent = null
  );
    super.new(name, parent);
  endfunction


 //------------------------------------------------------------------------------
// run_phase
//
// Verify:
//   1. Initial reset state generated by tb_top.
//   2. Reset assertion after normal reset release: 1 -> 0.
//   3. Reset release again: 0 -> 1.
//------------------------------------------------------------------------------

task run_phase(uvm_phase phase);

  phase.raise_objection(this);

  `uvm_info(
    "RESET_TEST",
    "Starting asynchronous FIFO reset test",
    UVM_LOW
  )

  //--------------------------------------------------------------------------
  // Step 1: Wait for initial reset generated by tb_top.
  //
  // Initial reset normally performs:
  //
  //   wrst_n : 0 -> 1
  //   rrst_n : 0 -> 1
  //--------------------------------------------------------------------------

  wait_for_initial_reset_release();

  // Verify expected post-initial-reset status.
  check_initial_reset_state();

  // Wait one extra edge in each clock domain and confirm stability.
  @(posedge vif.wclk);
  @(posedge vif.rclk);

  check_initial_reset_state();

  //--------------------------------------------------------------------------
  // Step 2: Assert reset again after it has already been released.
  //
  // This creates the transition required for reset assertion coverage:
  //
  //   wrst_n : 1 -> 0
  //   rrst_n : 1 -> 0
  //
  // No write/read sequences are active in this reset test, so it is safe for
  // the test to drive resets directly.
  //--------------------------------------------------------------------------

  @(negedge vif.wclk);

  vif.wrst_n = 1'b0;
  vif.rrst_n = 1'b0;

  `uvm_info(
    "RESET_TEST",
    "Runtime reset asserted: wrst_n=0, rrst_n=0",
    UVM_LOW
  )

  // The DUT uses asynchronous resets. Wait a small time for nonblocking
  // assignments in reset blocks to update pointer and flag registers.
  #1ns;

  //--------------------------------------------------------------------------
  // Step 3: Check FIFO flags while reset is asserted.
  //--------------------------------------------------------------------------

  if (vif.wfull !== 1'b0) begin
    `uvm_error(
      "RESET_TEST",
      $sformatf(
        "Reset assertion check failed: expected wfull=0, actual=%0b",
        vif.wfull
      )
    )
  end

  if (vif.awfull !== 1'b0) begin
    `uvm_error(
      "RESET_TEST",
      $sformatf(
        "Reset assertion check failed: expected awfull=0, actual=%0b",
        vif.awfull
      )
    )
  end

  if (vif.rempty !== 1'b1) begin
    `uvm_error(
      "RESET_TEST",
      $sformatf(
        "Reset assertion check failed: expected rempty=1, actual=%0b",
        vif.rempty
      )
    )
  end

  if (vif.arempty !== 1'b0) begin
    `uvm_error(
      "RESET_TEST",
      $sformatf(
        "Reset assertion check failed: expected arempty=0, actual=%0b",
        vif.arempty
      )
    )
  end

  `uvm_info(
    "RESET_TEST",
    $sformatf(
      "Reset assertion verified: wfull=%0b awfull=%0b rempty=%0b arempty=%0b",
      vif.wfull,
      vif.awfull,
      vif.rempty,
      vif.arempty
    ),
    UVM_LOW
  )

  // Hold reset active for a few cycles in both independent clock domains.
  repeat (2) @(posedge vif.wclk);
  repeat (2) @(posedge vif.rclk);

  //--------------------------------------------------------------------------
  // Step 4: Release reset again.
  //
  // This creates:
  //
  //   wrst_n : 0 -> 1
  //   rrst_n : 0 -> 1
  //--------------------------------------------------------------------------

  vif.wrst_n = 1'b1;
  vif.rrst_n = 1'b1;

  `uvm_info(
    "RESET_TEST",
    "Runtime reset released: wrst_n=1, rrst_n=1",
    UVM_LOW
  )

  // Allow write and read local logic to settle after reset release.
  @(posedge vif.wclk);
  @(posedge vif.rclk);

  //--------------------------------------------------------------------------
  // Step 5: Verify post-reset state again.
  //--------------------------------------------------------------------------

  check_initial_reset_state();

  `uvm_info(
    "RESET_TEST",
    "Reset test completed successfully",
    UVM_LOW
  )

  phase.drop_objection(this);

endtask

endclass
