class fifo_write_sequence extends uvm_sequence#(fifo_transaction);
`uvm_object_utils(fifo_write_sequence)

fifo_transaction wtx;

// Number of write attempts generated by this sequence.
 int unsigned num_writes = 1;
  
function new(string name = "fifo_write_sequence");
super.new(name);
endfunction


task body();
wtx=fifo_transaction::type_id::create("wtx");

  for(int i =0; i<num_writes; i++) begin
  
  wtx.winc=1; 
  wtx.rinc=0;
  start_item(wtx);
  assert(wtx.randomize());
  `uvm_info("FIFO_WRITE_SEQUENCE", $sformatf ("Write transaction generated TX =%0s ",wtx.convert2string()), UVM_LOW)
  finish_item(wtx);


end
endtask
 endclass
