   class fifo_read_sequence extends uvm_sequence#(fifo_transaction);
`uvm_object_utils(fifo_read_sequence)

fifo_transaction tx;

// Number of read attempts generated by this sequence.
  int unsigned num_reads = 1;    
    
function new(string name = "fifo_read_sequence");
super.new(name);
endfunction

task body();
tx=fifo_transaction::type_id::create("tx");

  for(int i =0; i<num_reads; i++) begin
  tx.rinc=1;
  start_item(tx);
    `uvm_info("FIFO_READ_SEQUENCE", $sformatf ("Read sequence started"), UVM_LOW)
  finish_item(tx);
end
endtask
 endclass
